import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google"; // Correct import for Montserrat
import "./globals.css";
import AppWrapper from "@/context/AppDataContext";

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Google Montserrat font import with various weights
const montserrat = Montserrat({
  weight: ["300", "400", "500", "600", "700"], // Specify the weights you need
  subsets: ["latin"], // Subsets to optimize loading
  variable: "--font-montserrat", // Optional: Define a CSS variable
});

export const metadata: Metadata = {
  title: "FYP Portal-NUCES",
  description: "Generated by create next app",
  // viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Link to the favicon */}
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
      </head>
      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
